### ISSUE TITLE
Can't transfer funds from 1 wallet address L5ZjawG4SpoZ1vMNUMSL57FwzASqi4uh1zsi6sGguohoxeg4FimPNrS4Q1pY8UvuyXf24QzQSrpNVBGUDNjn5Byd88ZqFt

### ISSUE THREAD

**Issue by jpass022** [LYRA-Block-Lattice/Lyra-Core#13]
**Describe the bug**
Can't transfer funds from 1 wallet address using Nebula or the QT

**To Reproduce**
1. Try to send from this address and nothing happens

**Expected behavior**
I expect the coin transfer to another address to happen

**Screenshots**
wallet address - L5ZjawG4SpoZ1vMNUMSL57FwzASqi4uh1zsi6sGguohoxeg4FimPNrS4Q1pY8UvuyXf24QzQSrpNVBGUDNjn5Byd88ZqFt
Balances: LYR:823947600000000

![image](https://user-images.githubusercontent.com/5889788/126224191-e6a2dcd2-3336-4ce9-893d-ca81631b7240.png)

https://nebula.lyra.live/showblock/L5ZjawG4SpoZ1vMNUMSL57FwzASqi4uh1zsi6sGguohoxeg4FimPNrS4Q1pY8UvuyXf24QzQSrpNVBGUDNjn5Byd88ZqFt

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] - Windows 10.0 and Ubuntu 20.04
 - Browser [e.g. chrome, safari]  Chrome and Firefox

**Additional context**

**Comment by wizd** [comment]
this should be fixed by the latest release [2.2.5](https://github.com/LYRA-Block-Lattice/Lyra-Core/releases/tag/2.2.5). please retry.

**Comment by jpass022** [comment]
still won't send from this address...

**Comment by wizd** [comment]
I think this issue has been resolved [link](https://nebula.lyra.live/showblock/LTz7cCPv8mGWaEE7EAA1yfiKziaNn6wcS3b6dkfrb2cJo5sBuax7LbRpVRyn36QdfLTTqtAAibCk3EVNNxgoV4nKw6xjVv/158)
