### ISSUE TITLE
Problem with unstaking and unexpected fees

### ISSUE THREAD

**Issue by ChabG** [LYRA-Block-Lattice/Lyra-Core#16]
via cli no way to see the unstake date in UTC. I relied on nebula page (https://nebula.lyra.live/profit/LWwZfd1nwH7srS693TJLhVmwgfB9TvWJdSQ7A3X5nZunBsUu35U2FcPJHsjynEsTNHGUNLFFdaJkH9NzbAPntHzSpfFCQe)

For my particular account it disappeared off this page so assumed the stake period had finished. When i came to unstake it was hit with an unexpected 0.8% fee

Either bug on nebula page or date calc is wrong.

============================

Also check where the fee goes it. I was trying to work out if the node got the fee but it appeared not to. This was the node owner of the profiting account i staked to above:-
https://nebula.lyra.live/showblock/LUYMnp9uBpe9hDkW5Z6715Lpku24jtdzYgoLrFUnXanANZbtoVmYCYyXRuBLWTwEg7xpYWJJrthMVcYpfpVE5dBxWa2rHr

**Comment by wizd** [comment]
fixed by [commit](https://github.com/LYRA-Block-Lattice/Lyra-Core/commit/60dad331d5981fbeca131c3c77767c23fcb17e7e)
