### ISSUE TITLE
Fee for "Unstaking" not paid to corresponding Node Owner

### ISSUE THREAD

**Issue by ChabG** [LYRA-Block-Lattice/Lyra-Core#18]
On testnet i did a test of unstaking during the stake period. I was correctly charged 0.8% fee (16000)
https://nebulatestnet.lyra.live/showblock/LEodNAzdRTTrVzVmRxmFZTq2muU3fqV9mdXgNcMusSt8Ms34TRQDkaX5kwLskZ9JEdSxJtNPEr7AsfapusqFDKVgE7mMk1

But surely that fee should have been paid to the node owner as compensation for breaking contract. It appears not. That 16000 fee seems to have disappeared. Node owner address:-
https://nebulatestnet.lyra.live/showblock/LYSRCV7J6QKEZdYVJSxbJCGhW45Yf3DLL8CZssQZuPxJKxibxKTbvtS3mec4qkDYkDrVXLfQxp9tzmPqXEhUm9nxyxxoaE

Node profiting address:-
https://nebulatestnet.lyra.live/showblock/LW6FcY4uPqSqWnhvDJyTtmo31hxaaNhMb2baEcXdcaLnEyHyAMxtuxp2QLRGpFSVRtbNDscYem9jsJEFYT2wJ552uix1Eg

So bug is if user unstakes during stake period fee is charged to the users wallet but that fee is lost in the network and not paid to anyone- it should have gone to the node owner

**Comment by wizd** [comment]
The fee is redistributed to all nodes as a service reword:

https://nebulatestnet.lyra.live/showblock/Consolidation/6346
